import type { Metadata } from "next";
 import { Inter } from "next/font/google";
 
 const inter = Inter({ 
  weight: ["400", "500", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});
import "./globals.css";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${inter.className}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
