import type { Metadata } from "next";
<<<<<<< HEAD
 import { Inter } from "next/font/google";
 
 const inter = Inter({ 
  weight: ["400", "500", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});
import "./globals.css";

 
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

>>>>>>> 7d446605f14372f33441671404476fcc8a3b5563
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html
      lang="en"
      className={`h-full antialiased ${inter.className}`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
>>>>>>> 7d446605f14372f33441671404476fcc8a3b5563
    </html>
  );
}
